package nz.org.vincenzo.betadog.service;

import fr.whimtrip.ext.jwhthtmltopojo.HtmlToPojoEngine;
import nz.org.vincenzo.betadog.domain.Instrument;
import nz.org.vincenzo.betadog.domain.MainBoard;
import nz.org.vincenzo.betadog.enumeration.InstrumentFilter;
import nz.org.vincenzo.betadog.enumeration.SortOrder;
import nz.org.vincenzo.betadog.service.impl.ScrapeServiceImpl;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Spy;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * The test case for {@link ScrapeService}.
 *
 * @author Rey Vincent Babilonia
 */
@ExtendWith(MockitoExtension.class)
class ScrapeServiceTest {

    @Spy
    private HtmlToPojoEngine engine = HtmlToPojoEngine.create();

    @Mock
    private RestTemplate restTemplate;

    @InjectMocks
    private ScrapeServiceImpl scrapeService;

    @Test
    void getMainBoard() {
        String body = "<table class=\"responsive-table hidden-columns instruments-table\" id=\"instruments-table\">"
                      + "    <tbody>"
                      + "        <tr class=\"\" title=\"AFI\">"
                      + "            <td class=\"text-center\" data-title=\"Code\">"
                      + "                <a href=\"/instruments/AFI\">"
                      + "                    <strong class=\"\">AFI</strong>"
                      + "                </a>"
                      + "            </td>"
                      + "            <td data-title=\"Company\">"
                      + "                <span class=\"nowrap\">"
                      + "                    <a title=\"Australian Foundation Investment Company Limited\""
                      + " href=\"/companies/AFI\">Australian Foundation Investment Company Limited</a>"
                      + "                </span>"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Price\">"
                      + "                $6.500"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Change\" >"
                      + "                <span class=\"nobreak\">"
                      + "                    <span class=\"down\">"
                      + "                        <i class=\"fa fa-arrow-down\"/>-$0.350 / -5.11%</span>"
                      + "                </span>"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Volume\">"
                      + "                8,007"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Value\">"
                      + "                $52,538.93"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Capitalisation\">"
                      + "                $7,867,368,821"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"ChangePercent\" >"
                      + "                -5.10948905109489"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Type\">"
                      + "                CLOSEEND"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"GreenBond\">"
                      + "                false"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"TradeCount\">"
                      + "                18"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"CurrencyCode\">"
                      + "                NZD"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"IndexedCapitalisation\">"
                      + "                $81,033,898.86"
                      + "            </td>"
                      + "        </tr>"
                      + "        <tr class=\"\" title=\"AMP\">"
                      + "            <td class=\"text-center\" data-title=\"Code\">"
                      + "                <a href=\"/instruments/AMP\">"
                      + "                    <strong class=\"\">AMP</strong>"
                      + "                </a>"
                      + "            </td>"
                      + "            <td data-title=\"Company\">"
                      + "                <span class=\"nowrap\">"
                      + "                    <a title=\"AMP Limited\" href=\"/companies/AMP\">AMP Limited</a>"
                      + "                </span>"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Price\">"
                      + "                $1.500"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Change\" >"
                      + "                <span class=\"nobreak\">"
                      + "                    <span class=\"down\">"
                      + "                        <i class=\"fa fa-arrow-down\"/>-$0.160 / -9.64%</span>"
                      + "                </span>"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Volume\">"
                      + "                52,652"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Value\">"
                      + "                $80,233.79"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Capitalisation\">"
                      + "                $5,154,898,862"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"ChangePercent\" >"
                      + "                -9.63855421686747"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Type\">"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"GreenBond\">"
                      + "                false"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"TradeCount\">"
                      + "                90"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"CurrencyCode\">"
                      + "                NZD"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"IndexedCapitalisation\">"
                      + "                $64,436,235.77"
                      + "            </td>"
                      + "        </tr>"
                      + "        <tr class=\"\" title=\"ANZ\">"
                      + "            <td class=\"text-center\" data-title=\"Code\">"
                      + "                <a href=\"/instruments/ANZ\">"
                      + "                    <strong class=\"\">ANZ</strong>"
                      + "                </a>"
                      + "            </td>"
                      + "            <td data-title=\"Company\">"
                      + "                <span class=\"nowrap\">"
                      + "                    <a title=\"Australia and New Zealand Banking Group Limited\""
                      + " href=\"/companies/ANZ\">Australia and New Zealand Banking Group Limited</a>"
                      + "                </span>"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Price\">"
                      + "                $21.850"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Change\" >"
                      + "                <span class=\"nobreak\">"
                      + "                    <span class=\"down\">"
                      + "                        <i class=\"fa fa-arrow-down\"/>-$1.650 / -7.02%</span>"
                      + "                </span>"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Volume\">"
                      + "                50,826"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Value\">"
                      + "                $1,122,974.20"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Capitalisation\">"
                      + "                $61,970,476,671"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"ChangePercent\" >"
                      + "                -7.02127659574468"
                      + "            </td>"
                      + "            <td class=\"text-right\" data-title=\"Type\">"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"GreenBond\">"
                      + "                false"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"TradeCount\">"
                      + "                215"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"CurrencyCode\">"
                      + "                NZD"
                      + "            </td>"
                      + "            <td class=\"text-right hide\" data-title=\"IndexedCapitalisation\">"
                      + "                $446,187,432.03"
                      + "            </td>"
                      + "        </tr>"
                      + "    </tbody>"
                      + "</table>";

        ResponseEntity<String> responseEntity = mock(ResponseEntity.class);
        when(responseEntity.getBody()).thenReturn(body);
        when(responseEntity.getStatusCode()).thenReturn(HttpStatus.OK);
        when(restTemplate.getForEntity(eq("https://www.nzx.com/markets/NZSX"), eq(String.class)))
                .thenReturn(responseEntity);

        assertThat(scrapeService.getMainBoard().getSecurities())
                .hasSize(3)
                .first()
                .extracting("code", "company")
                .containsExactly("AFI", "Australian Foundation Investment Company Limited");

        verify(engine).adapter(MainBoard.class);
    }

    @Test
    void getInstrument() {
        ResponseEntity<String> responseEntity = mock(ResponseEntity.class);
        when(responseEntity.getBody()).thenReturn(getAIR());
        when(responseEntity.getStatusCode()).thenReturn(HttpStatus.OK);
        when(restTemplate.getForEntity(eq("https://www.nzx.com/instruments/AIR"), eq(String.class)))
                .thenReturn(responseEntity);

        Instrument instrument = scrapeService.getInstrument("AIR");

        assertThat(instrument)
                .extracting("snapshot.code", "snapshot.company", "snapshot.instrumentType",
                        "performance.open", "performance.high", "performance.low",
                        "fundamental.priceToEarningsRatio", "fundamental.earningsPerShare")
                .containsExactly("AIR", "Air New Zealand Limited (NS)", "Ordinary Shares",
                        2.060, 2.055, 1.950, 10.570, 0.195);

        verify(engine).adapter(Instrument.class);
    }

    @Test
    void getInstruments() {
        prepareInstruments();

        List<Instrument> instruments = scrapeService.getInstruments(InstrumentFilter.ALL, SortOrder.DEFAULT);

        assertThat(instruments)
                .hasSize(5)
                .first()
                .extracting("snapshot.code", "snapshot.company", "snapshot.instrumentType",
                        "performance.open", "performance.high", "performance.low",
                        "fundamental.priceToEarningsRatio", "fundamental.earningsPerShare")
                .containsExactly("AIR", "Air New Zealand Limited (NS)", "Ordinary Shares",
                        2.060, 2.055, 1.950,
                        10.570, 0.195);

        verify(engine, times(5)).adapter(Instrument.class);
    }

    @Test
    void getEquityInstrumentsByPERatio() {
        prepareInstruments();

        List<Instrument> instruments = scrapeService.getInstruments(InstrumentFilter.EQUITIES, SortOrder.PE_RATIO);

        assertThat(instruments)
                .hasSize(3)
                .first()
                .extracting("snapshot.code", "snapshot.company", "snapshot.instrumentType",
                        "performance.open", "performance.high", "performance.low",
                        "fundamental.priceToEarningsRatio", "fundamental.earningsPerShare")
                .containsExactly("SUM", "Summerset Group Holdings Limited", "Ordinary Shares",
                        7.613, 7.58, 7.09,
                        9.92, 0.775);

        verify(engine, times(5)).adapter(Instrument.class);
    }

    @Test
    void getFundInstrumentsByEPS() {
        prepareInstruments();

        List<Instrument> instruments = scrapeService.getInstruments(InstrumentFilter.FUNDS, SortOrder.EPS);

        assertThat(instruments)
                .hasSize(2)
                .first()
                .extracting("snapshot.code", "snapshot.company", "snapshot.instrumentType",
                        "performance.open", "performance.high", "performance.low",
                        "fundamental.priceToEarningsRatio", "fundamental.earningsPerShare")
                .containsExactly("ASD", "Smartshares Australian Dividend ETF", "Index Fund",
                        1.494, 1.485, 1.369,
                        11.52, 0.13);

        verify(engine, times(5)).adapter(Instrument.class);
    }

    private static String getAIR() {
        return "<div class=\"small-12 medium-9 columns content\">"
               + "    <section class=\"instrument-snapshot \">"
               + "        <div class=\"row\">"
               + "            <div class=\"small-12 medium-5 columns\">"
               + "                <h2>"
               + "                    AIR"
               + "                </h2>"
               + "                <h1>"
               + "                    $1.950"
               + "                </h1>"
               + "                <span class=\"down\"><i class=\"fa fa-arrow-down\"></i>-$0.110 / -5.34%</span>"
               + "                <small>52 Week Change:"
               + "                    <span class=\"down\"><i class=\"fa fa-arrow-down\"></i>-$0.450 / -19.79%</span>"
               + "                </small>"
               + "            </div>"
               + "            <div class=\"small-12 medium-7 columns\">"
               + "                <table class=\"no-style\">"
               + "                    <tbody>"
               + "                    <tr>"
               + "                        <td><strong>Instrument Name</strong></td>"
               + "                        <td>"
               + "                            Air New Zealand Limited (NS) Ordinary Shares"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>Issued By</strong></td>"
               + "                        <td>"
               + "                            <a href=\"/companies/AIR\">Air New Zealand Limited (NS)</a>"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>ISIN</strong></td>"
               + "                        <td>NZAIRE0001S2</td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>Type</strong></td>"
               + "                        <td>Ordinary Shares</td>"
               + "                    <tr>"
               + "                    </tbody>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </section>"
               + ""
               + "    <div class=\"row\">"
               + "        <div class=\"small-12 medium-12 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Activity</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>Trading status</strong></td>"
               + "                        <td class=\"text-right\">Trading</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Trades</strong></td>"
               + "                        <td class=\"text-right\">3351</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Value</strong></td>"
               + "                        <td class=\"text-right\">$10,498,104.33</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Volume</strong></td>"
               + "                        <td class=\"text-right\">5,286,116</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Capitalisation (000s)</strong></td>"
               + "                        <td class=\"text-right\">"
               + "                            $2,189,480"
               + "                        </td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Performance</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>Open</strong></td>"
               + "                        <td class=\"text-right\">$2.060</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>High</strong></td>"
               + "                        <td class=\"text-right\">$2.055</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Low</strong></td>"
               + "                        <td class=\"text-right\">$1.950</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>High Bid</strong></td>"
               + "                        <td class=\"text-right\">$1.940</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Low Offer</strong></td>"
               + "                        <td class=\"text-right\">$1.960</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Fundamental</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>P/E</strong></td>"
               + "                        <td class=\"text-right\">10.570</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>EPS</strong></td>"
               + "                        <td class=\"text-right\">$0.195</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>NTA</strong></td>"
               + "                        <td class=\"text-right\">$1.630</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Gross Div Yield</strong></td>"
               + "                        <td class=\"text-right\">14.833%</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Securities Issued</strong></td>"
               + "                        <td class=\"text-right\">1,122,810,044</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </div>"
               + "</div>";
    }

    private static String getSUM() {
        return "<div class=\"small-12 medium-9 columns content\">"
               + "    <section class=\"instrument-snapshot \">"
               + "        <div class=\"row\">"
               + "            <div class=\"small-12 medium-5 columns\">"
               + "                <h2>"
               + "                    SUM"
               + "                </h2>"
               + "                <h1>"
               + "                    $7.180"
               + "                </h1>"
               + "                <span class=\"down\">"
               + "                                        <i class=\"fa fa-arrow-down\"/>-$0.433 / -5.69%</span>"
               + "                <small>52 Week Change:"
               + "                    <span class=\"up\">"
               + "                                            <i class=\"fa fa-arrow-up\"/>$1.102 / 19.22%</span>"
               + "                </small>"
               + "            </div>"
               + "            <div class=\"small-12 medium-7 columns\">"
               + "                <table class=\"no-style\">"
               + "                    <tbody>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Instrument Name</strong>"
               + "                        </td>"
               + "                        <td>"
               + "                            Summerset Group Holdings Limited Ordinary Shares"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Issued By</strong>"
               + "                        </td>"
               + "                        <td>"
               + "                            <a href=\"/companies/SUM\">Summerset Group Holdings Limited</a>"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>ISIN</strong>"
               + "                        </td>"
               + "                        <td>NZSUME0001S0</td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Type</strong>"
               + "                        </td>"
               + "                        <td>Ordinary Shares</td>"
               + "                    <tr>"
               + "                    </tbody>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </section>"
               + ""
               + "    <div class=\"row\">"
               + "        <div class=\"small-12 medium-12 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Activity</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Trading status</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">Trading</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Trades</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">381</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Value</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">$2,325,102.32</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Volume</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">325,081</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Capitalisation (000s)</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">"
               + "                            $1,628,623"
               + "                        </td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Performance</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Open</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">$7.613</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>High</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">$7.580</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Low</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">$7.090</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>High Bid</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">$7.160</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Low Offer</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">$7.190</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Fundamental</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>P/E</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">9.920</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>EPS</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">$0.775</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>NTA</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">$5.020</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Gross Div Yield</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">1.834%</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td>"
               + "                            <strong>Securities Issued</strong>"
               + "                        </td>"
               + "                        <td class=\"text-right\">226,827,675</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </div>"
               + "</div>";
    }

    private static String getZEL() {
        return "<div class=\"small-12 medium-9 columns content\">"
               + "    <section class=\"instrument-snapshot \">"
               + "        <div class=\"row\">"
               + "            <div class=\"small-12 medium-5 columns\">"
               + "                <h2>"
               + "                    ZEL"
               + "                </h2>"
               + "                <h1>"
               + "                    $4.060"
               + "                </h1>"
               + "                <span class=\"down\"><i class=\"fa fa-arrow-down\"></i>-$0.010 / -0.25%</span>"
               + "                <small>52 Week Change:"
               + "                    <span class=\"down\"><i class=\"fa fa-arrow-down\"></i>-$2.234 / -35.59%</span>"
               + "                </small>"
               + "            </div>"
               + "            <div class=\"small-12 medium-7 columns\">"
               + "                <table class=\"no-style\">"
               + "                    <tbody>"
               + "                    <tr>"
               + "                        <td><strong>Instrument Name</strong></td>"
               + "                        <td>"
               + "                            Z Energy Limited Ordinary Shares"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>Issued By</strong></td>"
               + "                        <td>"
               + "                            <a href=\"/companies/ZEL\">Z Energy Limited</a>"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>ISIN</strong></td>"
               + "                        <td>NZZELE0001S1</td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>Type</strong></td>"
               + "                        <td>Ordinary Shares</td>"
               + "                    <tr>"
               + "                    </tbody>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </section>"
               + ""
               + "    <div class=\"row\">"
               + "        <div class=\"small-12 medium-12 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Activity</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>Trading status</strong></td>"
               + "                        <td class=\"text-right\">Trading</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Trades</strong></td>"
               + "                        <td class=\"text-right\">1157</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Value</strong></td>"
               + "                        <td class=\"text-right\">$2,892,236.88</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Volume</strong></td>"
               + "                        <td class=\"text-right\">712,488</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Capitalisation (000s)</strong></td>"
               + "                        <td class=\"text-right\">"
               + "                            $1,624,000"
               + "                        </td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Performance</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>Open</strong></td>"
               + "                        <td class=\"text-right\">$4.070</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>High</strong></td>"
               + "                        <td class=\"text-right\">$4.180</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Low</strong></td>"
               + "                        <td class=\"text-right\">$4.020</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>High Bid</strong></td>"
               + "                        <td class=\"text-right\">$4.050</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Low Offer</strong></td>"
               + "                        <td class=\"text-right\">$4.080</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Fundamental</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>P/E</strong></td>"
               + "                        <td class=\"text-right\">22.300</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>EPS</strong></td>"
               + "                        <td class=\"text-right\">$0.183</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>NTA</strong></td>"
               + "                        <td class=\"text-right\">$0.060</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Gross Div Yield</strong></td>"
               + "                        <td class=\"text-right\">16.039%</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Securities Issued</strong></td>"
               + "                        <td class=\"text-right\">400,000,000</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </div>"
               + "</div>";
    }

    private static String getNZC() {
        return "<div class=\"small-12 medium-9 columns content\">"
               + "    <section class=\"instrument-snapshot \">"
               + "        <div class=\"row\">"
               + "            <div class=\"small-12 medium-5 columns\">"
               + "                <h2>"
               + "                    NZC"
               + "                </h2>"
               + "                <h1>"
               + "                    $2.966"
               + "                </h1>"
               + "                <span class=\"down\"><i class=\"fa fa-arrow-down\"></i>-$0.001 / -0.03%</span>"
               + "                <small>52 Week Change:"
               + "                    <span class=\"down\"><i class=\"fa fa-arrow-down\"></i>-$0.009 / -0.30%</span>"
               + "                </small>"
               + "            </div>"
               + "            <div class=\"small-12 medium-7 columns\">"
               + "                <table class=\"no-style\">"
               + "                    <tbody>"
               + "                    <tr>"
               + "                        <td><strong>Instrument Name</strong></td>"
               + "                        <td>"
               + "                            Smartshares NZ Cash ETF Units"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>Issued By</strong></td>"
               + "                        <td>"
               + "                            <a href=\"/companies/NZC\">Smartshares NZ Cash ETF</a>"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>ISIN</strong></td>"
               + "                        <td>NZNZCE0001S1</td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>Type</strong></td>"
               + "                        <td>Index Fund</td>"
               + "                    <tr>"
               + "                    </tbody>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </section>"
               + ""
               + "    <div class=\"row\">"
               + "        <div class=\"small-12 medium-12 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Activity</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>Trading status</strong></td>"
               + "                        <td class=\"text-right\">Trading</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Trades</strong></td>"
               + "                        <td class=\"text-right\">38</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Value</strong></td>"
               + "                        <td class=\"text-right\">$2,565.66</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Volume</strong></td>"
               + "                        <td class=\"text-right\">865</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Capitalisation (000s)</strong></td>"
               + "                        <td class=\"text-right\">"
               + "                            $174,738"
               + "                        </td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Performance</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>Open</strong></td>"
               + "                        <td class=\"text-right\">$2.967</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>High</strong></td>"
               + "                        <td class=\"text-right\">$2.966</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Low</strong></td>"
               + "                        <td class=\"text-right\">$2.966</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>High Bid</strong></td>"
               + "                        <td class=\"text-right\">$2.965</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Low Offer</strong></td>"
               + "                        <td class=\"text-right\">$2.967</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Fundamental</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>P/E</strong></td>"
               + "                        <td class=\"text-right\">52.990</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>EPS</strong></td>"
               + "                        <td class=\"text-right\">$0.056</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>NTA</strong></td>"
               + "                        <td class=\"text-right\">$2.965</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Gross Div Yield</strong></td>"
               + "                        <td class=\"text-right\">2.718%</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Securities Issued</strong></td>"
               + "                        <td class=\"text-right\">58,913,712</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </div>"
               + "</div>";
    }

    private static String getASD() {
        return "<div class=\"small-12 medium-9 columns content\">"
               + "    <section class=\"instrument-snapshot \">"
               + "        <div class=\"row\">"
               + "            <div class=\"small-12 medium-5 columns\">"
               + "                <h2>"
               + "                    ASD"
               + "                </h2>"
               + "                <h1>"
               + "                    $1.377"
               + "                </h1>"
               + "                <span class=\"down\"><i class=\"fa fa-arrow-down\"></i>-$0.117 / -7.83%</span>"
               + "                <small>52 Week Change:"
               + "                    <span class=\"down\"><i class=\"fa fa-arrow-down\"></i>-$0.084 / -6.23%</span>"
               + "                </small>"
               + "            </div>"
               + "            <div class=\"small-12 medium-7 columns\">"
               + "                <table class=\"no-style\">"
               + "                    <tbody>"
               + "                    <tr>"
               + "                        <td><strong>Instrument Name</strong></td>"
               + "                        <td>"
               + "                            Smartshares Australian Dividend ETF Units"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>Issued By</strong></td>"
               + "                        <td>"
               + "                            <a href=\"/companies/ASD\">Smartshares Australian Dividend ETF</a>"
               + "                        </td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>ISIN</strong></td>"
               + "                        <td>NZASDE0001S1</td>"
               + "                    <tr>"
               + "                    <tr>"
               + "                        <td><strong>Type</strong></td>"
               + "                        <td>Index Fund</td>"
               + "                    <tr>"
               + "                    </tbody>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </section>"
               + ""
               + "    <div class=\"row\">"
               + "        <div class=\"small-12 medium-12 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Activity</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>Trading status</strong></td>"
               + "                        <td class=\"text-right\">Trading</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Trades</strong></td>"
               + "                        <td class=\"text-right\">90</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Value</strong></td>"
               + "                        <td class=\"text-right\">$46,568.25</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Volume</strong></td>"
               + "                        <td class=\"text-right\">33,427</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Capitalisation (000s)</strong></td>"
               + "                        <td class=\"text-right\">"
               + "                            $23,656"
               + "                        </td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Performance</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>Open</strong></td>"
               + "                        <td class=\"text-right\">$1.494</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>High</strong></td>"
               + "                        <td class=\"text-right\">$1.485</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Low</strong></td>"
               + "                        <td class=\"text-right\">$1.369</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>High Bid</strong></td>"
               + "                        <td class=\"text-right\">$1.365</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Low Offer</strong></td>"
               + "                        <td class=\"text-right\">$1.371</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + ""
               + "        <div class=\"small-12 medium-6 large-4 columns\">"
               + "            <div class=\"panel callout instrument-info \">"
               + "                <h4>Fundamental</h4>"
               + "                <table class=\"no-style\">"
               + "                    <tr>"
               + "                        <td><strong>P/E</strong></td>"
               + "                        <td class=\"text-right\">11.520</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>EPS</strong></td>"
               + "                        <td class=\"text-right\">$0.130</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>NTA</strong></td>"
               + "                        <td class=\"text-right\">$1.543</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Gross Div Yield</strong></td>"
               + "                        <td class=\"text-right\">3.774%</td>"
               + "                    </tr>"
               + "                    <tr>"
               + "                        <td><strong>Securities Issued</strong></td>"
               + "                        <td class=\"text-right\">17,179,541</td>"
               + "                    </tr>"
               + "                </table>"
               + "            </div>"
               + "        </div>"
               + "    </div>"
               + "</div>";
    }

    private void prepareInstruments() {
        String body = "<table class=\"responsive-table hidden-columns instruments-table\" id=\"instruments-table\">"
                      + "    <tbody>"
                      + "    <tr class=\"\" title=\"AIR\">"
                      + "        <td class=\"text-center\" data-title=\"Code\">"
                      + "            <a href=\"/instruments/AIR\"><strong class=\"\">AIR</strong></a>"
                      + "        </td>"
                      + "        <td data-title=\"Company\">"
                      + "            <span class=\"nowrap\">"
                      + "                <a title=\"Air New Zealand Limited (NS)\" href=\"/companies/AIR\">Air New Zealand Limited (NS)</a>"
                      + "            </span>"
                      + "        </td>"
                      + "    </tr>"
                      + "    <tr class=\"\" title=\"ASD\">"
                      + "        <td class=\"text-center\" data-title=\"Code\">"
                      + "            <a href=\"/instruments/ASD\"><strong class=\"\">ASD</strong></a>"
                      + "        </td>"
                      + "        <td data-title=\"Company\">"
                      + "            <span class=\"nowrap\">"
                      + "                <a title=\"Smartshares Australian Dividend ETF\" href=\"/companies/ASD\">Smartshares Australian Dividend ETF</a>"
                      + "            </span>"
                      + "        </td>"
                      + "    </tr>"
                      + "    <tr class=\"\" title=\"NZC\">"
                      + "        <td class=\"text-center\" data-title=\"Code\">"
                      + "            <a href=\"/instruments/NZC\"><strong class=\"\">NZC</strong></a>"
                      + "        </td>"
                      + "        <td data-title=\"Company\">"
                      + "            <span class=\"nowrap\">"
                      + "                <a title=\"Smartshares NZ Cash ETF\" href=\"/companies/NZC\">Smartshares NZ Cash ETF</a>"
                      + "            </span>"
                      + "        </td>"
                      + "    </tr>"
                      + "    <tr class=\"\" title=\"SUM\">"
                      + "        <td class=\"text-center\" data-title=\"Code\">"
                      + "            <a href=\"/instruments/SUM\"><strong class=\"\">SUM</strong></a>"
                      + "        </td>"
                      + "        <td data-title=\"Company\">"
                      + "            <span class=\"nowrap\">"
                      + "                <a title=\"Summerset Group Holdings Limited\" href=\"/companies/SUM\">Summerset Group Holdings Limited</a>"
                      + "            </span>"
                      + "        </td>"
                      + "    </tr>"
                      + "    <tr class=\"\" title=\"ZEL\">"
                      + "        <td class=\"text-center\" data-title=\"Code\">"
                      + "            <a href=\"/instruments/ZEL\"><strong class=\"\">ZEL</strong></a>"
                      + "        </td>"
                      + "        <td data-title=\"Company\">"
                      + "            <span class=\"nowrap\">"
                      + "                <a title=\"Z Energy Limited\" href=\"/companies/ZEL\">Z Energy Limited</a>"
                      + "            </span>"
                      + "        </td>"
                      + "    </tr>"
                      + "    </tbody>"
                      + "</table>";

        ResponseEntity<String> mainBoard = mock(ResponseEntity.class);
        when(mainBoard.getBody()).thenReturn(body);
        when(mainBoard.getStatusCode()).thenReturn(HttpStatus.OK);
        when(restTemplate.getForEntity(eq("https://www.nzx.com/markets/NZSX"), eq(String.class))).thenReturn(mainBoard);

        ResponseEntity<String> air = mock(ResponseEntity.class);
        when(air.getBody()).thenReturn(getAIR());
        when(air.getStatusCode()).thenReturn(HttpStatus.OK);
        when(restTemplate.getForEntity(eq("https://www.nzx.com/instruments/AIR"), eq(String.class)))
                .thenReturn(air);

        ResponseEntity<String> asd = mock(ResponseEntity.class);
        when(asd.getBody()).thenReturn(getASD());
        when(asd.getStatusCode()).thenReturn(HttpStatus.OK);
        when(restTemplate.getForEntity(eq("https://www.nzx.com/instruments/ASD"), eq(String.class))).thenReturn(asd);

        ResponseEntity<String> nzc = mock(ResponseEntity.class);
        when(nzc.getBody()).thenReturn(getNZC());
        when(nzc.getStatusCode()).thenReturn(HttpStatus.OK);
        when(restTemplate.getForEntity(eq("https://www.nzx.com/instruments/NZC"), eq(String.class))).thenReturn(nzc);

        ResponseEntity<String> sum = mock(ResponseEntity.class);
        when(sum.getBody()).thenReturn(getSUM());
        when(sum.getStatusCode()).thenReturn(HttpStatus.OK);
        when(restTemplate.getForEntity(eq("https://www.nzx.com/instruments/SUM"), eq(String.class))).thenReturn(sum);

        ResponseEntity<String> zel = mock(ResponseEntity.class);
        when(zel.getBody()).thenReturn(getZEL());
        when(zel.getStatusCode()).thenReturn(HttpStatus.OK);
        when(restTemplate.getForEntity(eq("https://www.nzx.com/instruments/ZEL"), eq(String.class))).thenReturn(zel);
    }
}
