language: java
jdk: openjdk11
dist: xenial
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build

notifications:
  email: false

deploy:
  provider: heroku
  api_key: $API_KEY
  app:
    master: beta-dog
  run:
    - "heroku config:add VERSION_NUMBER=$VERSION_NUMBER"
