logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui-custom.html

spring:
  cache:
    cache-names:
      - mainBoard
      - instruments
    caffeine:
      spec:
        - maximumSize: 500
        - expireAfterAccess: 300s
