version: '3.7'
services:
  api:
    build:
      context: ./../../build
      dockerfile: Dockerfile
      args:
        app_version: ${APP_VERSION}
    image: beta-dog:${APP_VERSION}
    container_name: beta-dog
    ports:
      - 8080:8080
